In [1]:
import numpy as np

In [2]:
a = np.random.randn(100, 100)

In [3]:
a

array([[ 1.11523557, -0.13667162,  0.05268459, ..., -0.98647641,
         0.20869862,  0.94293251],
       [ 0.13680154, -2.24899434,  0.39997689, ...,  0.37072061,
         0.01220837,  2.58144982],
       [-1.69363008, -0.62093538,  0.64737515, ...,  0.52874134,
         1.56783945, -1.3819523 ],
       ..., 
       [ 0.475155  ,  2.29097559,  0.43065581, ...,  0.72397608,
        -1.22803762, -0.61511376],
       [-0.68461525, -1.46037064,  0.73237746, ...,  0.62337663,
         0.29923087, -0.02876289],
       [-1.13227583, -0.91549444,  0.26815891, ..., -1.11401368,
        -0.21874602,  0.40209997]])

In [4]:
a?

In [5]:
np.random.randn?

In [10]:
%run ../pydata-book/ch03/ipython_bug.py

AssertionError: 

In [11]:
%debug

> /Users/aenfield/work/pydata-book/ch03/ipython_bug.py(9)throws_an_exception()
      8     b = 6
----> 9     assert(a + b == 10)
     10 

ipdb> a
ipdb> a
ipdb> u
> /Users/aenfield/work/pydata-book/ch03/ipython_bug.py(13)calling_things()
     12     works_fine()
---> 13     throws_an_exception()
     14 

ipdb> d
> /Users/aenfield/work/pydata-book/ch03/ipython_bug.py(9)throws_an_exception()
      8     b = 6
----> 9     assert(a + b == 10)
     10 

ipdb> u
> /Users/aenfield/work/pydata-book/ch03/ipython_bug.py(13)calling_things()
     12     works_fine()
---> 13     throws_an_exception()
     14 

ipdb> u
> /Users/aenfield/work/pydata-book/ch03/ipython_bug.py(15)<module>()
     13     throws_an_exception()
     14 
---> 15 calling_things()

ipdb> d
> /Users/aenfield/work/pydata-book/ch03/ipython_bug.py(13)calling_things()
     12     works_fine()
---> 13     throws_an_exception()
     14 

ipdb> d
> /Users/aenfield/work/pydata-book/ch03/ipython_bug.py(9)throws_an_exception()
      8  

In [17]:
%run -d ../pydata-book/ch03/ipython_bug.py

Breakpoint 1 at /Users/aenfield/work/pydata-book/ch03/ipython_bug.py:1
NOTE: Enter 'c' at the ipdb>  prompt to continue execution.
> /Users/aenfield/work/pydata-book/ch03/ipython_bug.py(1)<module>()
1---> 1 def works_fine():
      2     a = 5
      3     b = 6

ipdb> q


In [3]:
import sys

def set_trace():
    from IPython.core.debugger import Pdb
    Pdb(color_scheme='Linux').set_trace(sys._getframe().f_back)
    
def debug(f, *args, **kwargs):
    from IPython.core.debugger import Pdb
    pdb = Pdb(color_scheme='Linux')
    return pdb.runcall(f, *args, **kwargs)

In [7]:
def throw_an_assertion():
    a = 5
    b = 6
    set_trace()
    assert(a + b == 10)
    
throw_an_assertion()

> <ipython-input-7-3fbc0317f976>(5)throw_an_assertion()
      4     set_trace()
----> 5     assert(a + b == 10)
      6 

ipdb> !a
5
ipdb> !b
6
ipdb> !a + !b
*** SyntaxError: invalid syntax
ipdb> q


BdbQuit: 

In [1]:
def f(x, y, z=1):
    tmp = x + y
    return tmp / z

In [ ]:
debug(f, 1, 2, z=3)

> <ipython-input-1-b1f62d757512>(2)f()
      1 def f(x, y, z=1):
----> 2     tmp = x + y
      3     return tmp / z

--KeyboardInterrupt--


In [14]:
def run_experiment(niter=100):
    K = 100
    results = []
    for _ in range(niter):
        mat = np.random.randn(K, K)
        max_eigenvalue = np.abs(np.linalg.eigvals(mat)).max()
        results.append(max_eigenvalue)
    return results

In [16]:
%prun -l 7 -s cumulative run_experiment()

In [19]:
x = np.array([[13, 8, 6], [9, 7, 4], [7, 4, 0], [15, 6, 3]])
x

array([[13,  8,  6],
       [ 9,  7,  4],
       [ 7,  4,  0],
       [15,  6,  3]])

In [20]:
y = np.array([[3, 4, 2]])
y

array([[3, 4, 2]])

In [21]:
y.T

array([[3],
       [4],
       [2]])

In [26]:
x.dot(y.T)

array([[83],
       [63],
       [37],
       [75]])

In [23]:
x.shape

(4, 3)

In [24]:
y.shape

(1, 3)

In [25]:
y.T.shape

(3, 1)

In [27]:
N = 1000000

In [29]:
import random
%timeit samples = [random.normalvariate(0, 1) for _ in range(N)]

1 loops, best of 3: 1.16 s per loop


In [30]:
%timeit np.random.normal(size=N)

10 loops, best of 3: 41.1 ms per loop


In [31]:
position = 0
walk = [position]
walk

[0]

In [32]:
steps = 1000

In [34]:
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)
    
walk

[0,
 1,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 8,
 7,
 8,
 9,
 10,
 11,
 10,
 11,
 12,
 13,
 14,
 15,
 14,
 13,
 14,
 13,
 12,
 13,
 14,
 13,
 14,
 15,
 16,
 15,
 14,
 15,
 14,
 13,
 12,
 11,
 12,
 13,
 12,
 11,
 10,
 9,
 10,
 9,
 10,
 11,
 10,
 9,
 8,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 14,
 15,
 16,
 15,
 16,
 17,
 18,
 19,
 20,
 19,
 18,
 17,
 16,
 15,
 16,
 15,
 14,
 15,
 16,
 17,
 16,
 17,
 16,
 17,
 16,
 15,
 16,
 15,
 14,
 13,
 14,
 15,
 14,
 13,
 12,
 11,
 12,
 13,
 12,
 11,
 10,
 9,
 8,
 9,
 10,
 9,
 8,
 7,
 6,
 7,
 6,
 5,
 4,
 5,
 6,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 13,
 14,
 15,
 14,
 13,
 12,
 13,
 12,
 11,
 12,
 11,
 10,
 11,
 10,
 11,
 12,
 13,
 12,
 11,
 10,
 11,
 10,
 11,
 12,
 11,
 12,
 11,
 10,
 9,
 8,
 7,
 6,
 5,
 6,
 5,
 4,
 3,
 2,
 1,
 0,
 1,
 2,
 1,
 0,
 1,
 2,
 3,
 2,
 3,
 4,
 3,
 4,
 3,
 2,
 1,
 2,
 1,
 0,
 -1,
 -2,
 -1,
 -2,
 -1,
 -2,
 -3,
 -4,
 -5,
 -6,
 -5,
 -4,
 -3,
 -2,
 -3,
 -4,
 -5,
 -6,
 -5,
 -4,
 -3,
 -4,
 -3,
 -4,
 -3,
 -4,
 -5,
 

In [36]:
np.random.randint?

In [42]:
nsteps = 1000
draws = np.random.randint(0, 2, size=nsteps)
draws[:10]

array([0, 0, 0, 1, 0, 1, 0, 1, 1, 0])

In [43]:
steps = np.where(draws > 0, 1, -1)
steps[:10]

array([-1, -1, -1,  1, -1,  1, -1,  1,  1, -1])

In [44]:
walk = steps.cumsum()
walk[:10]

array([-1, -2, -3, -2, -3, -2, -3, -2, -1, -2])

In [45]:
walk.min()

-3

In [46]:
walk.max()

46

In [47]:
# for each element in walk, return True or False depending on whether
# it the current value is 10+ steps from the origin of zero
np.abs(walk) >= 10

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False,

In [48]:
# and 'first crossing time' - the first time the current value gets
# more than a certain distance - like 10 - from the origin, is just
# the first index of the maximum value in the array, and here True
# is the maximum value - argmax gives us this.
(np.abs(walk) >= 10).argmax()

67

In [49]:
walk[0]

-1

In [51]:
walk[5]

-2

In [52]:
walk[66]

9

In [53]:
walk[67]

10

In [54]:
walk[68]

9

In [56]:
walk[65:70]

array([ 8,  9, 10,  9,  8])

Now let's do many random walks - like 5000 - using a matrix. The code's almost the same as before, w/ just a few differences where we specify the shape, I think.

In [59]:
np.cumsum?

In [61]:
nwalks = 5000
nsteps = 1000
draws = np.random.randint(0, 2, size=(nwalks, nsteps))  # 0 or 1
steps = np.where(draws > 0, 1, -1)
walks = steps.cumsum(1) # '1' changes the axis - w/ '1' we 'sum over columns for each of the rows' and by default we 'sum over the rows for each of the columns'

In [62]:
walks

array([[  1,   2,   1, ..., -42, -41, -40],
       [  1,   0,  -1, ..., -14, -15, -16],
       [ -1,   0,  -1, ...,  22,  23,  22],
       ..., 
       [  1,   0,   1, ...,   2,   3,   4],
       [  1,   2,   1, ...,   2,   1,   2],
       [  1,   0,   1, ...,   4,   5,   4]])

In [63]:
walks.max()

122

In [64]:
walks.min()

-126

There's a bit more at the very end of chapter 4, with code that calculates the minimum crossing time across all rows.