In [1]:
import numpy as np

# Implement perceptron?

In [2]:
learning_rate = 0.1

In [3]:
def y_hat(w, x):
    return w.T.dot(x)

In [4]:
#X = np.array([1,1,0,1,2,1,1,-1,-1]).reshape(3,3)
X = np.array([5,10,0,10,20,0,30,60,0]).reshape(3,3)

#y = np.array([0,0,0])
y = np.array([1,1,0])

w = np.zeros(9).reshape(3,3)

print(X)
print(y)
print(w)

[[ 5 10  0]
 [10 20  0]
 [30 60  0]]
[1 1 0]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [5]:
for i in range(3):
    yhi = y_hat(w[i], X[i])
    for j in range(3):
        w[i,j] = w[i,j] + learning_rate*(yhi - y[i])*X[i,j]
    print("Updated weights for output neuron {}".format(i))
    print(w)

Updated weights for output neuron 0
[[-0.5 -1.   0. ]
 [ 0.   0.   0. ]
 [ 0.   0.   0. ]]
Updated weights for output neuron 1
[[-0.5 -1.   0. ]
 [-1.  -2.   0. ]
 [ 0.   0.   0. ]]
Updated weights for output neuron 2
[[-0.5 -1.   0. ]
 [-1.  -2.   0. ]
 [ 0.   0.   0. ]]


In [6]:
print([y_hat(w[i], X[i]) for i in range(3)])
print(y)

[-12.5, -50.0, 0.0]
[1 1 0]


# MNIST with ANNs

In [24]:
#from sklearn.datasets import fetch_mldata
#from sklearn.model_selection import train_test_split
#from sklearn.preprocessing import StandardScaler
from tensorflow.examples.tutorials.mnist import input_data
import tensorflow as tf

In [25]:
mnist = input_data.read_data_sets('/tmp/data/')

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting /tmp/data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [32]:
X_train = mnist.train.images
X_test = mnist.test.images
y_train = mnist.train.labels.astype('int')
y_test = mnist.test.labels.astype('int')

In [27]:
feature_columns = tf.contrib.learn.infer_real_valued_columns_from_input(X_train_scaled)

In [28]:
dnn_clf = tf.contrib.learn.DNNClassifier(hidden_units=[300,100],
                                         n_classes=10,
                                         feature_columns=feature_columns)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_task_type': None, '_task_id': 0, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x12443fc88>, '_master': '', '_num_ps_replicas': 0, '_num_worker_replicas': 0, '_environment': 'local', '_is_chief': True, '_evaluation_master': '', '_tf_config': gpu_options {
  per_process_gpu_memory_fraction: 1
}
, '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_secs': 600, '_session_config': None, '_save_checkpoints_steps': None, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_model_dir': '/var/folders/w7/xw8t3rd52f39l5b7349hvlth0000gn/T/tmpq8yb3k83'}


In [29]:
dnn_clf = tf.contrib.learn.SKCompat(dnn_clf)

In [30]:
dnn_clf.fit(X_train, y_train, batch_size=50, steps=40000)

Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Saving checkpoints for 1 into /var/folders/w7/xw8t3rd52f39l5b7349hvlth0000gn/T/tmpq8yb3k83/model.ckpt.
INFO:tensorflow:loss = 2.36622, step = 1
INFO:tensorflow:global_step/sec: 252.402
INFO:tensorflow:loss = 0.35656, step = 101 (0.398 sec)
INFO:tensorflow:global_step/sec: 219.422
INFO:tensorflow:loss = 0.30984, step = 201 (0.457 sec)
INFO:tensorflow:global_step/sec: 251.184
INFO:tensorflow:loss = 0.389507, step = 301 (0.397 sec)
INFO:tensorflow:global_step/sec: 241.704
INFO:tensorflow:loss = 0.206082, step = 401 (0.413 sec)
INFO:tensorflow:global_step/sec: 228.012
INFO:tensorflow:loss = 0.228415, step = 

INFO:tensorflow:loss = 0.0157104, step = 7601 (0.447 sec)
INFO:tensorflow:global_step/sec: 221.845
INFO:tensorflow:loss = 0.00887934, step = 7701 (0.451 sec)
INFO:tensorflow:global_step/sec: 230.537
INFO:tensorflow:loss = 0.004644, step = 7801 (0.440 sec)
INFO:tensorflow:global_step/sec: 163.94
INFO:tensorflow:loss = 0.00480093, step = 7901 (0.604 sec)
INFO:tensorflow:global_step/sec: 214.451
INFO:tensorflow:loss = 0.00298529, step = 8001 (0.467 sec)
INFO:tensorflow:global_step/sec: 146.12
INFO:tensorflow:loss = 0.0352609, step = 8101 (0.693 sec)
INFO:tensorflow:global_step/sec: 184.513
INFO:tensorflow:loss = 0.0193492, step = 8201 (0.534 sec)
INFO:tensorflow:global_step/sec: 155.132
INFO:tensorflow:loss = 0.0738289, step = 8301 (0.647 sec)
INFO:tensorflow:global_step/sec: 152.938
INFO:tensorflow:loss = 0.00353999, step = 8401 (0.651 sec)
INFO:tensorflow:global_step/sec: 165.104
INFO:tensorflow:loss = 0.00563597, step = 8501 (0.606 sec)
INFO:tensorflow:global_step/sec: 165.282
INFO:ten

INFO:tensorflow:loss = 0.000758206, step = 15801 (0.409 sec)
INFO:tensorflow:global_step/sec: 260.931
INFO:tensorflow:loss = 0.000422364, step = 15901 (0.383 sec)
INFO:tensorflow:global_step/sec: 266.426
INFO:tensorflow:loss = 0.00536683, step = 16001 (0.375 sec)
INFO:tensorflow:global_step/sec: 230.107
INFO:tensorflow:loss = 0.00357606, step = 16101 (0.437 sec)
INFO:tensorflow:global_step/sec: 231.266
INFO:tensorflow:loss = 0.000113444, step = 16201 (0.431 sec)
INFO:tensorflow:global_step/sec: 264.719
INFO:tensorflow:loss = 0.00501625, step = 16301 (0.376 sec)
INFO:tensorflow:global_step/sec: 254.338
INFO:tensorflow:loss = 0.00188417, step = 16401 (0.394 sec)
INFO:tensorflow:global_step/sec: 263.037
INFO:tensorflow:loss = 0.00451473, step = 16501 (0.380 sec)
INFO:tensorflow:global_step/sec: 233.625
INFO:tensorflow:loss = 0.00305584, step = 16601 (0.428 sec)
INFO:tensorflow:global_step/sec: 266.355
INFO:tensorflow:loss = 0.00218611, step = 16701 (0.375 sec)
INFO:tensorflow:global_step/

INFO:tensorflow:loss = 0.00233325, step = 23901 (0.580 sec)
INFO:tensorflow:global_step/sec: 180.606
INFO:tensorflow:loss = 0.000807125, step = 24001 (0.559 sec)
INFO:tensorflow:global_step/sec: 159.458
INFO:tensorflow:loss = 0.000683314, step = 24101 (0.622 sec)
INFO:tensorflow:global_step/sec: 182.19
INFO:tensorflow:loss = 0.00210294, step = 24201 (0.548 sec)
INFO:tensorflow:global_step/sec: 185.747
INFO:tensorflow:loss = 0.000199466, step = 24301 (0.538 sec)
INFO:tensorflow:global_step/sec: 159.682
INFO:tensorflow:loss = 0.0025477, step = 24401 (0.629 sec)
INFO:tensorflow:global_step/sec: 193.22
INFO:tensorflow:loss = 0.0007561, step = 24501 (0.517 sec)
INFO:tensorflow:global_step/sec: 190.506
INFO:tensorflow:loss = 0.000384708, step = 24601 (0.525 sec)
INFO:tensorflow:global_step/sec: 194.547
INFO:tensorflow:loss = 0.000570174, step = 24701 (0.513 sec)
INFO:tensorflow:global_step/sec: 197.453
INFO:tensorflow:loss = 0.00077887, step = 24801 (0.506 sec)
INFO:tensorflow:global_step/se

INFO:tensorflow:loss = 0.000234414, step = 32001 (0.469 sec)
INFO:tensorflow:global_step/sec: 247.975
INFO:tensorflow:loss = 0.000264576, step = 32101 (0.402 sec)
INFO:tensorflow:global_step/sec: 221.343
INFO:tensorflow:loss = 0.00113266, step = 32201 (0.451 sec)
INFO:tensorflow:global_step/sec: 252.362
INFO:tensorflow:loss = 0.000527548, step = 32301 (0.396 sec)
INFO:tensorflow:global_step/sec: 268.5
INFO:tensorflow:loss = 0.000386476, step = 32401 (0.371 sec)
INFO:tensorflow:global_step/sec: 254.667
INFO:tensorflow:loss = 0.000604182, step = 32501 (0.393 sec)
INFO:tensorflow:global_step/sec: 268.055
INFO:tensorflow:loss = 0.000159568, step = 32601 (0.374 sec)
INFO:tensorflow:global_step/sec: 266.656
INFO:tensorflow:loss = 0.00130351, step = 32701 (0.373 sec)
INFO:tensorflow:global_step/sec: 269.416
INFO:tensorflow:loss = 0.000986373, step = 32801 (0.372 sec)
INFO:tensorflow:global_step/sec: 264.503
INFO:tensorflow:loss = 0.000615686, step = 32901 (0.377 sec)
INFO:tensorflow:global_st

INFO:tensorflow:Loss for final step: 0.000506187.


SKCompat()

In [33]:
from sklearn.metrics import accuracy_score

y_pred = dnn_clf.predict(X_test)
accuracy_score(y_test, y_pred['classes'])

INFO:tensorflow:Restoring parameters from /var/folders/w7/xw8t3rd52f39l5b7349hvlth0000gn/T/tmpq8yb3k83/model.ckpt-40000


0.98229999999999995

In [35]:
from sklearn.metrics import log_loss

y_pred_proba = y_pred['probabilities']
log_loss(y_test, y_pred_proba)

0.07504156431783314